### PR TITLE
Update 01-basic_usage.php

### PR DESCRIPTION
**Pull request by kijato**
It was not clear from the previous version how to get the data of the sheets.

### CODE REVIEW

**Comment by shuchkin** [comment]
No, your version long and not optimal 1) ```#``` as comment start is bad, 2) 99% XLS is one sheet document

**Comment by kijato** [comment]
I'm pretty sure about that my version is not perfect but could you help me make it better? In my opinion, it is advisable to make the example such that it is not necessary to browse through the original source code for the solution, that I see how can I access the others sheets' data:
_public function rows(**$sheetNum = 0**, $limit = 0)_

In my world it is common for a workbook to have several/many worksheets so it is normal in my mind and in my "solution".

**Comment by shuchkin** [comment]
https://github.com/shuchkin/simplexls?tab=readme-ov-file#basic-methods

**Comment by kijato** [comment]
You are right, I am blind... 😁

**Pull request closed without merging**
